"""
schema.py - The domain taxonomy and the strict JSON contract we hold the LLM to.

Two jobs:
  1. Hardcode the 7 life-domains a plan can cover. The taxonomy is ours, not the
     model's - the model only gets to pick *which* of these are relevant.
  2. Define and enforce the JSON shape the model must return. LLMs are unreliable
     narrators, so nothing from the API is trusted until it has passed through
     `validate_plan_response()` below.
"""

from __future__ import annotations

from typing import Any

# --------------------------------------------------------------------------
# Domain taxonomy - fixed, never generated by the model
# --------------------------------------------------------------------------

DOMAINS: tuple[str, ...] = (
    "documents_id",
    "housing",
    "income_employment",
    "healthcare",
    "legal_compliance",
    "support_network",
    "mental_stability",
)

# Human-readable labels used in the UI and in prompts.
DOMAIN_LABELS: dict[str, str] = {
    "documents_id": "Documents & ID",
    "housing": "Housing",
    "income_employment": "Income & Employment",
    "healthcare": "Healthcare",
    "legal_compliance": "Legal & Compliance",
    "support_network": "Support Network",
    "mental_stability": "Mental Stability",
}

DOMAIN_DESCRIPTIONS: dict[str, str] = {
    "documents_id": "ID cards, birth certificates, social security / national insurance "
                    "numbers, proof of address - the paperwork other things depend on.",
    "housing": "Somewhere to sleep tonight, and somewhere stable to live after that.",
    "income_employment": "Money coming in: benefits, work, training, banking.",
    "healthcare": "Registering with a doctor, prescriptions, insurance, ongoing conditions.",
    "legal_compliance": "Obligations with deadlines: court dates, reporting requirements, "
                        "visa or residency conditions, debts.",
    "support_network": "People and organisations who can help - family, community groups, caseworkers.",
    "mental_stability": "Sleep, routine, coping, counselling - the things that make the rest possible.",
}

URGENCY_LEVELS: tuple[str, ...] = ("high", "medium", "low")

# Used to sort steps so urgent things float to the top of each domain.
URGENCY_RANK: dict[str, int] = {"high": 0, "medium": 1, "low": 2}

# The model answers with one of these. "clarify" lets it decline to guess when
# the intake text is too thin to plan from (see prompts.py).
RESPONSE_TYPES: tuple[str, ...] = ("plan", "clarify")


# --------------------------------------------------------------------------
# JSON schema handed to the Gemini API as `response_format`
# --------------------------------------------------------------------------
#
# Note we use ONE object schema with optional `steps` / `question` keys rather
# than a oneOf/anyOf union. Structured-output implementations handle flat object
# schemas far more reliably than unions, so we keep the schema simple and do the
# "is this a plan or a question?" branching ourselves in validate_plan_response().

# maxLength on every string field, and minItems/maxItems on the steps array,
# are not decorative - they're a defence against a real failure mode found
# during testing: a smaller/faster model (gemini-3.1-flash-lite) ignored the
# prose instruction "1-2 calm sentences" and produced several hundred words of
# rambling text in `summary` alone, burning the entire output-token budget
# before ever reaching the `steps` array. That left the JSON truncated
# mid-string, with no closing brace, so it failed to parse at all. A JSON
# Schema constraint is enforced by the API during generation itself, so it
# holds regardless of how well a given model follows free-text instructions.
STEP_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "maxLength": 60,
            "description": "Short unique slug for this step, e.g. 'replace_photo_id'.",
        },
        "domain": {
            "type": "string",
            "enum": list(DOMAINS),
            "description": "Which of the seven life domains this step belongs to.",
        },
        "title": {
            "type": "string",
            "maxLength": 80,
            "description": "Short imperative title, e.g. 'Replace your photo ID'.",
        },
        "description": {
            "type": "string",
            "maxLength": 500,
            "description": (
                "2-4 plain sentences (under 500 characters) on what to actually do. "
                "No invented organisation names, phone numbers, addresses or legal "
                "requirements."
            ),
        },
        "depends_on": {
            "type": "array",
            "items": {"type": "string", "maxLength": 60},
            "description": "ids of steps that must realistically happen first. Empty list if none.",
        },
        "urgency": {"type": "string", "enum": list(URGENCY_LEVELS)},
        "est_time": {
            "type": "string",
            "maxLength": 40,
            "description": "Rough human estimate, e.g. '30 minutes', '1-2 weeks'.",
        },
    },
    "required": ["id", "domain", "title", "description", "depends_on", "urgency", "est_time"],
}

PLAN_RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": list(RESPONSE_TYPES),
            "description": "'plan' if there is enough detail to plan from, else 'clarify'.",
        },
        "question": {
            "type": "string",
            "maxLength": 300,
            "description": "Only when type is 'clarify': one warm, specific question to ask.",
        },
        "summary": {
            "type": "string",
            "maxLength": 280,
            "description": (
                "Only when type is 'plan': exactly 1-2 short, calm sentences framing "
                "the plan. Under 280 characters - this is a brief framing line, not a "
                "message of encouragement."
            ),
        },
        "steps": {
            "type": "array",
            "items": STEP_SCHEMA,
            "minItems": 3,
            "maxItems": 15,
            "description": "Only when type is 'plan'. Between 3 and 15 steps.",
        },
    },
    "required": ["type"],
    # Only `type` is unconditionally required, because the two response shapes
    # ("plan" has summary+steps, "clarify" has question) share one flat schema
    # rather than a oneOf/anyOf union - see the module-level note above on why.
    # But that alone leaves a real gap: a schema-compliant response can satisfy
    # `required: ["type"]` with JUST `{"type": "plan"}` and nothing else, no
    # steps at all. That is not hypothetical - it is exactly what happened in
    # production (confirmed on multiple models) once the model found a shorter
    # valid completion than actually writing the plan. This if/then closes the
    # gap without a full union: when type is "plan", summary and steps become
    # required; when it's anything else, question does.
    "if": {"properties": {"type": {"const": "plan"}}},
    "then": {"required": ["type", "summary", "steps"]},
    "else": {"required": ["type", "question"]},
}


# --------------------------------------------------------------------------
# Defensive validation
# --------------------------------------------------------------------------


class PlanValidationError(ValueError):
    """Raised when the model's JSON is structurally unusable.

    llm.py catches this and retries the call once before surfacing a friendly
    error to the user.
    """


def _clean_str(value: Any) -> str:
    """Coerce a value to a stripped string, tolerating None and numbers."""
    if value is None:
        return ""
    return str(value).strip()


def validate_plan_response(raw: Any) -> tuple[dict[str, Any], list[str]]:
    """Validate and normalise a decoded JSON response from the planner call.

    Returns `(clean_response, warnings)`. Warnings are non-fatal repairs we made
    - a dropped bad step, a dangling dependency - and the plan is still usable.
    Anything genuinely unusable raises PlanValidationError instead.
    """
    warnings: list[str] = []

    if not isinstance(raw, dict):
        raise PlanValidationError("Top-level JSON was not an object.")

    resp_type = _clean_str(raw.get("type")).lower()
    if resp_type not in RESPONSE_TYPES:
        # Be forgiving: infer the type from what the payload actually contains.
        if isinstance(raw.get("steps"), list) and raw["steps"]:
            resp_type = "plan"
            warnings.append("Response was missing a 'type' field; assumed it was a plan.")
        elif _clean_str(raw.get("question")):
            resp_type = "clarify"
            warnings.append("Response was missing a 'type' field; assumed it was a question.")
        else:
            raise PlanValidationError(f"Unknown response type: {raw.get('type')!r}")

    # --- the "I need more information" branch ----------------------------
    if resp_type == "clarify":
        question = _clean_str(raw.get("question"))
        if not question:
            raise PlanValidationError("Clarify response had no question text.")
        return {"type": "clarify", "question": question}, warnings

    # --- the plan branch --------------------------------------------------
    steps_raw = raw.get("steps")
    if not isinstance(steps_raw, list) or not steps_raw:
        raise PlanValidationError("Plan response contained no steps.")

    clean_steps: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    for index, item in enumerate(steps_raw):
        if not isinstance(item, dict):
            warnings.append(f"Dropped step #{index + 1}: it was not a JSON object.")
            continue

        step_id = _clean_str(item.get("id"))
        title = _clean_str(item.get("title"))
        domain = _clean_str(item.get("domain")).lower()

        # A step with no id or no title is not salvageable.
        if not step_id or not title:
            warnings.append(f"Dropped step #{index + 1}: missing an id or a title.")
            continue

        # An off-taxonomy domain is a hallucination we cannot render. Drop the
        # step rather than silently filing it under the wrong heading.
        if domain not in DOMAINS:
            warnings.append(f"Dropped step {step_id!r}: unknown domain {domain!r}.")
            continue

        # Duplicate ids would break dependency resolution and checkbox state.
        if step_id in seen_ids:
            suffixed = f"{step_id}_{index}"
            warnings.append(f"Step id {step_id!r} appeared twice; renamed one to {suffixed!r}.")
            step_id = suffixed
        seen_ids.add(step_id)

        urgency = _clean_str(item.get("urgency")).lower()
        if urgency not in URGENCY_LEVELS:
            urgency = "medium"  # safe middle default rather than a crash

        depends_on = item.get("depends_on")
        if not isinstance(depends_on, list):
            depends_on = []
        depends_on = [_clean_str(d) for d in depends_on if _clean_str(d)]

        clean_steps.append(
            {
                "id": step_id,
                "domain": domain,
                "title": title,
                "description": _clean_str(item.get("description")),
                "depends_on": depends_on,
                "urgency": urgency,
                "est_time": _clean_str(item.get("est_time")) or "unknown",
            }
        )

    if not clean_steps:
        raise PlanValidationError("Every step in the response was invalid.")

    # Resolve dependencies only *after* we know the final set of ids.
    valid_ids = {s["id"] for s in clean_steps}
    for step in clean_steps:
        kept: list[str] = []
        for dep in step["depends_on"]:
            if dep == step["id"]:
                warnings.append(f"Step {step['id']!r} depended on itself; ignored.")
            elif dep in valid_ids:
                kept.append(dep)
            else:
                warnings.append(f"Step {step['id']!r} depended on unknown step {dep!r}; ignored.")
        step["depends_on"] = kept

    _break_dependency_cycles(clean_steps, warnings)

    return (
        {
            "type": "plan",
            "summary": _clean_str(raw.get("summary")),
            "steps": clean_steps,
        },
        warnings,
    )


def _break_dependency_cycles(steps: list[dict[str, Any]], warnings: list[str]) -> None:
    """Remove dependency cycles in place.

    A cycle (A waits for B, B waits for A) would leave both steps permanently
    shown as "blocked" with no way for the user to make progress. We resolve it
    with a Kahn-style pass: repeatedly place any step whose dependencies are all
    already placed; if nothing can be placed but steps remain, the remainder
    contains a cycle, so we cut one step free and carry on.
    """
    by_id = {s["id"]: s for s in steps}
    placed: set[str] = set()
    remaining = list(by_id)

    while remaining:
        ready = [sid for sid in remaining if set(by_id[sid]["depends_on"]) <= placed]

        if not ready:
            # Deadlock: everything left is waiting on something else left.
            stuck = remaining[0]
            warnings.append(
                f"Step {stuck!r} was part of a circular dependency; "
                "its prerequisites were cleared."
            )
            by_id[stuck]["depends_on"] = []
            ready = [stuck]

        for sid in ready:
            placed.add(sid)
            remaining.remove(sid)


def sort_steps(steps: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Order steps for display: most urgent first, stable within an urgency level."""
    return sorted(steps, key=lambda s: URGENCY_RANK.get(s.get("urgency", "medium"), 1))


def domains_in_plan(steps: list[dict[str, Any]]) -> list[str]:
    """Which taxonomy domains this plan actually touches, in canonical order.

    Domains the model judged irrelevant simply never appear, so the UI never
    renders an empty tab.
    """
    present = {s["domain"] for s in steps}
    return [d for d in DOMAINS if d in present]
